### ISSUE TITLE
Mentions of deleted accounts cause confusion in tweets data

### ISSUE THREAD

**Issue by llsigerson** [ropensci/rtweet#120]
This is relatively minor. I found that mentions of accounts that have been deleted cause some discrepancies in the tweets dataframes. The "text" variable will still display the deleted account, but it's not displayed in the remaining variables where it normally would be (e.g., "reply_to_user_id", "mentions_user_id", etc.). 

I assume this discrepancy comes directly from the API, but if there were a good place to just mention it in the documentation that could be helpful. Took me a little bit to figure out what was going on.

The discrepancy can be found easily in some of my recent tweets: get_timeline("llsigerson").

**Comment by mkearney** [comment]
It's definitely due to Twitter's API design choices, but I'm very glad you made this an issue. Users should understand that ***screen names are not not static and thus only unique at a cross-section of time***. Twitter users can change their screen name with relative ease and frequency), and Twitter's APIs only seem to recognize screen names *as identifiers* when they happen to match the user's screen name ***at the time of any given request.***

**Comment by llsigerson** [comment]
yeah, that all makes sense, thanks for the follow up!

**Comment by alexpghayes** [comment]
FWIW the v2 endpoint looks like it should help with this by adding explicit data about who is mentioned in a tweet, and encoding this as a user id rather than a screen name
