### ISSUE TITLE
Invalid or expired token. 

### ISSUE THREAD

**Issue by jcmundy** [ropensci/rtweet#141]
I keep getting the following error instead of a browser and log-in:

Auto-refreshing stale OAuth token.
Error in `$<-.data.frame`(`*tmp*`, app, value = "google") : 
  replacement has 1 row, data has 0
In addition: Warning message:
89 - Invalid or expired token.

**Comment by mkearney** [comment]
@jcmundy That probably means you've got an ".httr-oauth" file in your current working directory. I need to include an additional check that can catch this error, but until I do...you should be able to avoid this error by removing the ".httr-oauth" file.

``` r
file.remove(".httr-oauth")
```

If there's **not** an ".httr-oauth" file, that'll return a warning like this:

``` r
> file.remove(".httr-oauth")
[1] FALSE
Warning message:
In file.remove(".httr-oauth") :
  cannot remove file '.httr-oauth', reason 'No such file or directory'
```

Otherwise, you may have to restart your R session once the file is removed. Then, <fingers crossed>, everything should work fine. And once it does, it should save the path/token for future use (avoiding future instances where you may have an ".httr-oauth" file in a working directory while using rtweet).

**Comment by AmeliaMN** [comment]
This solution worked for me (restarting my R session was required).

**Comment by jcmundy** [comment]
Ah yes, it looks like I never responded.  This also worked for me and I have been successfully using rtweet since.  Thanks!

**Comment by miken32** [comment]
Yes, I had this problem because I'd used an OAuth process with a different library. Removing the file did resolve the issue; does this mean we can only use one OAuth application at a time?
