### ISSUE TITLE
creating token, 

### ISSUE THREAD

**Issue by thoughtfulbloke** [ropensci/rtweet#264]
This, I suspect, relates to several other issues, but is following a different enough path I thought I should report it by itself

### Problem

I was getting "Warning: 89 - Invalid or expired token" on a machine. R 3.5.0 Mac, rtweet 0.6.7.9000

Created completely new app on twitter, checked off details and created token with 

```
twitter_token <- create_token(
  app = app_name,
  consumer_key = api_key,
  consumer_secret = api_secret,
  access_token = access_token,
  access_secret = access_token_secret)
```

still get "Warning: 89 - Invalid or expired token"

but if I run the rtweet command with an explicit token=twitter_token it works fine

I check

```
identical(twitter_token, get_token())
```
and it returned FALSE, which suggests something is going wrong with the environmental variable

I delete all the .rtweet_etc files in the home directory, recreate the twitter token, and it still doesn't work by itself, but it does after restarting RStudio so redoing the loading the environment step.

So it looks to me like there is something going wrong in the handling of the token as an environmental variable.

**Comment by mkearney** [comment]
Hrmm, that is interesting! So am I correct in saying that the token works for you as expected right away (i.e., `token = twitter_token` works fine), but the environment variable only works upon resetting RStudio?

If so, then you may want to inspect your ".Renviron" file(s) (it's possible that you have a local '.Renviron' file with an old path that is overriding your home directory one, or maybe there is some other weirdness going on in there) and check to make sure there is no ".httr-oauth" file in your current working directory. Otherwise, my guess is that either (a) you work on a PC [and there's something I just don't understand about environment variables work on PCs] or (b) this is an unfortunately side effect of OS-agnostic environment variable complexity.
