### ISSUE TITLE
How I can get location(from user profile) and geo location of tweet?Interested specifically on South Africa users.I have tried using lookupcoords( ) function but I still get below error:Error in search_tweets("lang:es", geocode = Southafrica_coord, n = 20) :    object 'Southafrica_coord' not found

### ISSUE THREAD

**Issue by ghost** [ropensci/rtweet#289]
### Reproduce the problem

``` r
## insert code here

```

### rtweet version

``` r
## copy/paste output
packageVersion("rtweet")
```

### Session info

``` r
## copy/paste output
sessionInfo()
```

### Token

``` r
## copy/paste output
rtweet::get_token()
```

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment]
Reading this thread more carefully, it looks like @Arf9999 provided a solution, so I'm going to close for now.
