### ISSUE TITLE
Waiting about 71 minutes

### ISSUE THREAD

**Issue by jantleon** [ropensci/rtweet#314]
Hello, I'm a Msc student using rtweet in order to search tweets about spanish elections. I'm trying to get tweets related to three hashtags: #eleccionesgenerales, #eleccionesgenerales28abril and #28deabril . I know that Twitter has a limit of 18000 tweets per 15 minutes and to solve that problem we can define retryonratelimit=TRUE, but this time I get the following message:

retry on rate limit...
waiting about 71 minutes...

71 minutes!? That's too much time... The expected behavior is only 15 minutes, not an hour and eleven minutes. The code I'm using is:

#Búsqueda de tweets
library (rtweet)
Convocatoriaelecciones <- search_tweets(
  "#28deabril OR #eleccionesgenerales OR #eleccionesgenerales28abril", n = 1000000, retryonratelimit = TRUE, type = "recent", include_rts = TRUE, lang = "es"
)

Thanks for your help and for your package, rTweet is really useful! :D

**Comment by Arf9999** [comment]
Are you using your own OAuth token or the built-in rtweet authorisation? The delay could be caused by rate-limiting of the rtweet twitter app itself.

You can try creating your own twitter app and token, which may resolve the issue.

Also, one thing to note. Your code is not going to surface any tweets that are newer than the time at which you started to run the script (because of the way that the search is done in rtweet - it searches backwards over time). If you need to monitor newer tweets, you'll need to run the search again after it has completed the 1000000 tweet search (which will take a long time - around 14 hours or so) as no tweets authored in those 14 hours will be captured.
