### ISSUE TITLE
Geo Location  and coordinates format 

### ISSUE THREAD

**Issue by orlandoandradeb** [ropensci/rtweet#322]
Hello 

I am studying mobility patters and I want to use twitter data to enrich my information. 
I see that there is a function  within "research_tweets"  called "geocode" but this   retunr the tweets near to a given coordinates but  relating  with the data of "Location"  that can be an entire city.  For example my location: Barcelona Spain.   

Is  there a way to get the coordinates of the tweets ? or filter that the research just give me the tweets with coordinates? 
I see that in  twiitter there is the option the available my location. I have wrote tweets  with my account with that option available and when I see the data in R there is not my coordinates in the data.

**Comment by orlandoandradeb** [comment]
Another issue, I have been comparing rtweet and twitteR package. One  important difference for my propouse is that the geo location data that I get from twitteR is divided in columds of lat  & lon . On the contrary  the data that I get from rtweet is on a colum "geo_coords" that has in format of  a vector the coordinates.  I am using  the function " complete.cases" to remove tweets without  coordinates. This works for the data from twitteR becasue there is display in separate colums just as in a dataframe but with rtweet  It doesnt work. Any suggestion how to  handle with this format ? I would like to pass it to separete colums. 

if somobody can giveme a hand with this  will be so nice. Thank you everyone.

**Comment by Arf9999** [comment]
First question: Twitter shows approximate geo coords only for accounts that have enabled it. Those coordinates that are reported by the API are not exact but will reflect an area which could be a town, city or suburb (this is for privacy purposes). Typically (from my experience) only 1-2% of tweets have geocoding.

What twitter will allow is for searches by geocode, and to achieve this, twitter will first check if the tweet is geocoded, and if not, will check whether a place can be extrapolated from the user's profile information. So you could, for example, search for tweets from the Barcelona area and twitter will deliver a lot of tweets that aren't geocoded because the users have "Barcelona" in their profile.

Second question: You just need to extract the lat and lon from the list in the "geo_coords" column:
You could use dplyr as in this example:
```

## We need dplyr and magrittr packages
install.packages("tidyverse")

library(tidyverse)  

##create an example rtweet dataframe
df <- rtweet::search_tweets("Donald Trump", n= 100) 

##filter out all results that have no geo_coords, and create new columns for lat and lon
df <- dplyr::filter(df, !is.na(place_type)) %>%  
          dplyr::mutate(lat = rtweet::flatten(geo_coords)[1],
                         lon = rtweet::flatten(geo_coords)[2]) 
```

**Comment by orlandoandradeb** [comment]
hello @Arf9999 thank you for your answer.  the code can filter using the columd "place_type" now I see that if there is a location information in a tweet this colum (place_type) will  have some data ("place_full_name" could be an option too). 

I have tried to use "is.na" too  to make a filter directly  taking the "geo_corrds" colum but doest work I guess becasue the type of data.  In the second part of the code  does not work neither 
%>%  
          dplyr::mutate(lat = rtweet::flatten(geo_coords)[1],
                         lon = rtweet::flatten(geo_coords)[2]) 

 when I want to separte the latitute and longitude the console gives me an error:   
"Error in rtweet::flatten(geo_coords) : is.data.frame(x) is not TRUE"
 
Another  thing,  I see that sometimes  the request gives you geo_coords and coords_coords whichs is the same information just flipped.  All this tweets has bbox_coords too. But some others just gives you bboox_coords.  What exaclty is bboox_coords ? I cant plot it neither because the same reasons it is  in a list. 

I am kind of frustrated becasue the way it gives you the data, this gives you 88 colums many of them with almost the same information and the geolocations puts in this format. 


thank you, I really appreciate it

**Comment by orlandoandradeb** [comment]
@Arf9999  thank you for your time. I just solve it with the  next funtion: 

lat_lng(x, coords = c("coords_coords", "bbox_coords", "geo_coords"))

**Comment by Arf9999** [comment]
Glad you got it sorted.

Just a point, my code should work if you pass the arguments correctly through the magrittr (i.e `%>%` pipe. If you want to use the dplyr or rtweet functions outside of the pipe, you'll need to include the dataframe name.  
e.g.  if 'df' is an rtweet dataframe:
'''df <- dplyr::mutate(df, lat = rtweet::flatten(geo_coords)[1],
lon = rtweet::flatten(geo_coords)[2])'''
The reason that using `is.na `doesn't work on geo_coords is that the "NAs" are contained in a list, so testing for NA will always return FALSE because the list exists.  That's why it is simpler to use `place_type' as a proxy. 

The reason that rtweet delivers so many columns, is because the twitter API delivers those fields in response to an API request.  Although many of the columns are unnecessary for much analysis, having a single structure for the results of different rtweet functions (e.g. search_tweets(), get_timeline() etc.) means that it is simpler to join, bind and check intersects of different results. 
It is simple enough to build a small script to remove extraneous columns.
