### ISSUE TITLE
search_fullarchive token

### ISSUE THREAD

**Issue by giorgiop2it** [ropensci/rtweet#328]
Hello,
which token must be inserted in search_fullarchive?

thank you 

Giorgio

**Comment by danweitzel** [comment]
Hi Giorgio, 

from the help file:
> 
token | A token associated with a user-created APP (requires a developer account), which is converted to a bearer token in order to make premium API requests
-- | --

You can set this token in the Twitter Dashboard when your application for a Developer account at Twitter was successful.
