### ISSUE TITLE
Multiple tokens

### ISSUE THREAD

**Issue by NataliaUC** [ropensci/rtweet#342]
Hi!
I am collecting a big amount of historical data for a research project. In my environment I have three tokens, but when I call the API it doesn't iterate among them. 
How can I set it so that it iterates and doesn't wait for 15 minutes?

**Comment by Arf9999** [comment]
Strictly speaking using multiple tokens is against the user terms of the API. 

However, iterating is fairly trivial, but won't occur automatically.

Are you using the premium API or the standard API? And, what function are you using that is being rate-limited?

**Comment by NataliaUC** [comment]
Hi! Thanks for your response!

I'm using standard APIs to collect followers ids (get_followers function). I know I should write a loop based on the API's rate limit, however, I'm not sure how to code it. Do you have any examples of how to iterate tokens?

Many thanks!!!

**Comment by Arf9999** [comment]
I'm not sure how comfortable you are with modifying functions, but the simplest way to do this would be by modifying the `get_followers_()` source code.

You can view the code like so: `rtweet:::get_followers_`. 
I'd definitely recommend that you copy and paste the code to make a new function before modifying it. You can then modify the function to accept a list of tokens rather than one, and iterate between them on ratelimit. 
The specific bit of code that you'd need to modify to iterate tokens would be the retryonratelimit check.

I'm wary to actually post any modified code, because, as I said, using multiple tokens is contrary to the twitter API terms and conditions.

**Comment by NataliaUC** [comment]
Many thanks for your response!

To be honest, I am not too comfortable modifying functions. I am taking a look at it right now and I am not sure that I'll be able to make the appropriate modification. In case I am not able to do it this way, is there any other method I could use?

I am looking at a post made by Michael Kearney saying that rtweet can cycle through tokens to navigate API rate limits. However, it might be a bit outdated as the post is from a couple of years ago.
[https://rpubs.com/mkearney/rtweet-tokens]

Unfortunately, given my own limitations, this is becoming more difficult than I hoped.

**Comment by Arf9999** [comment]
I understand that sometimes it is a bit complex to dive into someone else's code. 

I've never considered iterating tokens for followers or friends, and since there aren't unique sequential identifiers for these data, I guess that you'd have to use the `page` signifier from twitter's API.
Each call to the API will deliver up to 5000 followers, and a token will be ratelimited after 15 calls. You could try using `get_followers_()` and specifying the page number in each iteration, modifying the token every 15 calls.  I've not tried it, and I'm not 100% sure that it'd work.

**Comment by Arf9999** [comment]
Drop me an email at arf9999 <at> gmail and I'll send you a code snippet that may help.

**Comment by alexpghayes** [comment]
I wrote a package to help with this at https://github.com/alexpghayes/socialsampler.

**Comment by hadley** [comment]
Now mostly handled in #469. But I don't think rtweet should be in the business of helping you circumvent twitter's rate limits.

**Comment by alexpghayes** [comment]
FWIW `socialsampler` should also be thought of as deprecated, at least the multiple token handling.
