### ISSUE TITLE
Stops downloading data

### ISSUE THREAD

**Issue by acircleda** [ropensci/rtweet#364]
I am attempting to download all tweets tagged #TidyTuesday:

`tidy_tweets <- search_tweets(q = "#TidyTuesday", n=200000, retryonratelimit = TRUE)`

I am using my own API keys and access tokens.  Consistently, when it gets to 7% (896 observations), it stops downloading data. That's not even near the 18k limit. Is this an issue with rweet or Twitter?

**Comment by bpdeak** [comment]
Hi there, 

Did you ever find an answer to this? I'm experiencing the same thing right now. 

Thanks!!

**Comment by Arf9999** [comment]
search_tweets() uses the standard twitter API which only returns results from the past 9 or so days. 
So, around 1000 tweets about #tidytuesday, in one week looks about right.

**Comment by bpdeak** [comment]
Ah, so what you're saying is that if you say n=1800 or something, it'll download all of the ones from the past 9 days and that might not equal out to 1800, so the "Downloading 7%" which it stops at indicates that 7% is all that was available of the requested n from that time period?

**Comment by mkearney** [comment]
Yes, it is most likely because there aren't enough tweets in the standard search API time window (the past 6-9 days). In general, this is best tested by setting `n = 18000`

``` r
tidy_tweets <- search_tweets(q = "#TidyTuesday", n = 18000)
```

For larger downloads, though, it's not uncommon to have a disruption or some kind of rate limit misfire. It's not a bad idea to write a for-loop for requests that exceed the 15-minute rate limit (so when n > 18000). The for-loop will allow you to recover collected data (all previous iterations of loop) even when hitting an error. For more robust solutions, I'm slowly working [{rtweet.download}](https://github.com/mkearney/rtweet.download)
