### ISSUE TITLE
Drop follow/unfollow tests

### ISSUE THREAD

**Issue by hadley** [ropensci/rtweet#545]
@llrs what do you think about dropping these tests? We seem to commonly hit the higher level rate limits for following/unfollowing and I think the code is simple enough that it's probably ok to test manually when needed.

**Comment by llrs** [comment]
Today the packages has been tested 10 times, three of them on CI, I think this frequency won't happen once rtweet reaches a more stable state so the app won't hit the rate limits.  
We can reduce the number of tests but not dropping them completly. I don't think maintainers will remember to  manually run any tests on the future. Certainly I won't. But this test and retweeting tests frequently hit the limits/problems when done by the multiple CI machines too often/concurrently. 

Not sure what happens when the user is blocked. Is it difficult to solve it with Twitter? 
When I waited to get in touch with Twitter for a testing account I was hopping that Twitter could provide more margin for users created for testing. Not sure if this is possible (probably not) but rtweet might need to work with what it have.

**Comment by hadley** [comment]
It's now happened twice, and each time it blocks the user for three days (after I've logged in manually). I think we need to protect these tests so that they are not run by default. 

I think the chances of getting special treatment from twitter are quite low, unfortunately 😞

**Comment by hadley** [comment]
And it's locked again. I don't think the value that these two tests brings is worth the pain that they are currently causing.

**Comment by hadley** [comment]
I've left them in but skipped them with an informative warning.

**Comment by llrs** [comment]
Not sure if related but deleting tweets didn't work too: https://twitter.com/rtweet_test/status/1375423939283943429,

rate_limit() currently does not report anything for /friendships/update, /friendships/destroy/ and /friendships/create. There are currently 6 test for post_follow so when pushed there are 24. If the rate limit is 15/hour we need to reduce the test to 3

**Comment by hadley** [comment]
I'm deliberately not deleting that test tweet. Why does it matter?

**Comment by llrs** [comment]
Oh, then it is fine, it's just that I started seeing it and thought something else was not working well. But I see you added it recently as part of your commit on post_follow.
