### ISSUE TITLE
Misleading error messages when trying to add protected accounts to lists "* You aren't allowed to add members to this list. (104)"

### ISSUE THREAD

**Issue by simonheb** [ropensci/rtweet#592]
When I try to add a protected account to a list (which does not work of course). `rtweet` issues the warning
```
* You aren't allowed to add members to this list. (104)
```
In this particular case, the warning should of course be 
```
* You aren't allowed to add this user to any list
```

**Comment by llrs** [comment]
Hi @simonheb many thanks for this report. You are raising many issues overlooked that will improve the package usability. Certainly there are few tests about protected or blocked users. 

I will try to fix this, but I'm afraid there isn't a way to know if a user is protected via the Twitter API v1 so rtweet tries to add the member and returns the error provided by the API, which I agree, it is not informative. Will try to see if there is a way to provide better warnings for these cases.

**Comment by simonheb** [comment]
Let me know if these minor issue reports are not useful. Otherwise I will keep posting them:)

**Comment by llrs** [comment]
Don't stop posting them! I might be slower fixing them and I might have to leave some issues unattended for a while to focus on what I think is more important for the package.  But they are very useful because they make the usage of the package easier for all. They will also help to other users trying to understand what is happening with their code and what does their error message mean.

**Comment by llrs** [comment]
I forgot to close this issue I handled on https://github.com/ropensci/rtweet/commit/bc2b09d8a9a8f2ed6fde06b1ad6795603b6093e6 and later on #644 . Let me know if the solution doesn't work well .
