### ISSUE TITLE
post_message on MacOS does not work.

### ISSUE THREAD

**Issue by neuwirthe** [ropensci/rtweet#616]
rtweet has a problem. `post_tweet` workswithout and  with a media parameter, and posts images,
but `post_message` does not work at all.

For my example to work a Twitter account is needed and `rtweet`
has to be initialized.

`.Renviron` has to contain the environment variables 
`TWITTER_SCREEN_NAME` and `TWITTER_PAT`, `TWITTER_PAT` pointing to `~/.rtweet_token.rds`

This is with `rtweet` package vesion 0.7.0.9000 from guthub  in R 4.1.0 on MacOS 10.15.7

```
library(rtweet)
target_user <- "neuwirthe"
post_message("text only message",target_user) 
```

produces 

```
Error: Twitter API failed [400] * event.message_create.target.recipient_id: '' is not a valid Long (214)
```

**Comment by llrs** [comment]
Can you post your example using [reprex](https://reprex.tidyverse.org/) ? 
I tried with the account used for testing but I couldn't (not sure if because this is a bot account or something else, as the message was different from yours). 
Also if you could post your traceback() it would help to understand where does this error message originate, as it seems to come from Twitter's API and not from rtweet.

**Comment by neuwirthe** [comment]
The reprex probably will not work immediatelly because it still needs a configured Twitter access as described in my previous post.


``` r
library(rtweet)
target_user <- "neuwirthe"
post_message("Test mit rtweet, text only", target_user)
#> Error: Twitter API failed [400]
#>  * event.message_create.target.recipient_id: '' is not a valid Long (214)
```

<sup>Created on 2021-08-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by llrs** [comment]
Reprex uses your current configuration unless you specify it to not use it. But you didn't provide the `traceback()`. Currently it seems to be a problem on the Twitter api, unless you provide something pointing out to rtweet.
