### ISSUE TITLE
`search_tweets` tibble to original JSON

### ISSUE THREAD

**Issue by delvinso** [ropensci/rtweet#631]
Hi, apologies if I'm asking in the wrong place - is it possible to convert the tibble returned by `search_tweets`  into the original JSON (or as close to as possible) returned from twitter's API? To clarify I have already saved the csv using `write_as_csv`.

After playing around I think I've found my answer but if there is a better way please let me know:

1) read the csv back in using `read_twitter_csv`
2) `unflatten `the csv
3) use `jsonlite::toJSON` to dump the tibble as JSON 

Thank you!

**Comment by llrs** [comment]
Hi @delvinso, I don't understand why you need them back to the original JSON format, and I'm not sure the `unflatten` function returns the **original** JSON, I don't think so because the column names are changed on rtweet version 0.7.0. 

I would recommend to retrieve again the tweets via `lookup_tweets(statuses  = mycsv$ids, parse = FALSE)`. The `parse = FALSE` is important to keep the JSON as it is currently returned. 

I'm closing this as this is a question about rtweet and not about an issue with the software (although, if you had a use case why this could be needed, perhaps it could be added back on rtweet).
