### ISSUE TITLE
tweet_threading() errors uninformatively when passed a tweet status ID

### ISSUE THREAD

**Issue by alexpghayes** [ropensci/rtweet#633]
It is a little confusing that the following results in an error. Perhaps `tweet_threading()` could be modified to accept status IDs as inputs rather than data frames, to be more in line with the rest of `rtweet`?

``` r
library(rtweet)

seed_tweet_statusid <- "1458217774677954560"

tweet_threading(seed_tweet_statusid, traverse = "forwards")
#> Error: $ operator is invalid for atomic vectors
```

<sup>Created on 2021-11-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

I think it would also be valuable to add a comment to the documentation noting that `tweet_threading()` can only return tweets from a thread in the formal twitter sense (i.e. sequence of tweets by an author) rather than a thread as often used in the colloquial sense (formal thread + all the replies and any ongoing conversation there).

**Comment by llrs** [comment]
I changed it so that users do not need to call lookup_tweets (It is called internally) and changed the documentation as suggested.

I made it slightly faster, but if you make a query for such an old tweet (I changed the example tweet too), it will consume all your calls to the timeline endpoint as apparently it returns the most recent tweets first and only "up to 3,200 of a user's most recent Tweets".  I didn't document it (yet) as there is an endpoint on v2 for that might prevent this ...
