### ISSUE TITLE
Less observations when use  #search_tweets function. 

### ISSUE THREAD

**Issue by Sue596** [ropensci/rtweet#728]
install.packages("rtweet", repos = 'https://ropensci.r-universe.dev')
library(rtweet)
rtweet:::default_cached_auth()
auth_setup_default()  # the screen will show
# Authentication complete. Please close this page and return to R.
#use #Autism search 

tweetsAA <- search_tweets("#autismawareness",
                          n=10000,
                          lang="en",
                          include_rts = TRUE,
                          retryonratelimit = TRUE)

packageVersion("rtweet") 
[1] ‘0.7.0.9037’  

Hi, I am back.  I use the code to search the hastags in twitter. When I ran the same code, in the 2:00 pm today, I can got 346 observarions. But in the night, now 9:40 pm, I just got 186 observations. In fact, I think there should be more observrions, such as 5000 or more.  Could you please help to tell me the reason and help to issue it ?  Thank you so much.

**Comment by Arf9999** [comment]
The Twitter API version 1, which rtweet uses, returns search responses from the previous 8-9 days. Over time the returns will necessarily change as tweets age out of this period.  So first it is important to judge whether this is not just an indication of that.

Secondly, Twitter sometimes suppresses search results of misinformation or what it considers abusive content. In the case of a search for autism this may be an issue due to the antivax messaging around it.

I don't think that this is an issue with rtweet, but rather a Twitter issue.




________________________________
From: Sue596 ***@***.***>
Sent: Saturday, August 13, 2022 3:53:53 AM
To: ropensci/rtweet ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ropensci/rtweet] Less observations when use #search_tweets function. (Issue #728)


install.packages("rtweet", repos = 'https://ropensci.r-universe.dev')
library(rtweet)
rtweet:::default_cached_auth()
auth_setup_default() # the screen will show

Authentication complete. Please close this page and return to R.

#use #Autism search

tweetsAA <- search_tweets("#autismawareness",
n=10000,
lang="en",
include_rts = TRUE,
retryonratelimit = TRUE)

packageVersion("rtweet")
[1] ‘0.7.0.9037’

Hi, I am back. I use the code to search the hastags in twitter. When I ran the same code, in the 2:00 pm today, I can got 346 observarions. But in the night, now 9:40 pm, I just got 186 observations. In fact, I think there should be more observrions, such as 5000 or more. Could you please help to tell me the reason and help to issue it ? Thank you so much.

**Comment by llrs** [comment]
In addition to what @Arf9999 has said, it would be helpful if you explained why do you expect 5000 or more tweets.
Last, I want to encourage using the released version, as there were some bugs/issues fixed, you can do so with `install.packages("rtweet")`.

**Comment by Sue596** [comment]
oh, thank you so much. I install the package again then, I got 990 obs today. Seems better . Give my best wishes to all of you!

**Comment by LeonStumberger** [comment]
Hey, I am facing a similiar problem. I installed the newest available rtweet version (1.0.2) and the problem persists. 
It seems that there missing observations for some dates. 
Running this code
```
RTweet0916 <- search_tweets(q = "#KarlMay OR #Winnetou", 
                            n = Inf,
                            include_rts = F,
                            token = auth,
                            retryonratelimit = TRUE)
```
for example, it does not scrape tweets between the 13th and the 9th of September, even though an earlier try on the 14th of September collected tweets within this time span and a check on Twitter shows, that there have been a lot of Tweets posted. 

Thanks in advance for any suggestions on how to fix this!

**Comment by llrs** [comment]
Hi @LeonStumberger there is no garantee that the API returns all tweets, it just return a sample of tweets which match with the query. If you need all you'll need to search the full archive or monitor it via the streaming api.

**Comment by LeonStumberger** [comment]
Thanks for your quick response @llrs! 

Maybe it is common knowledge and I just dont know about it, but I feel like it could be handy if your vignettes and documentation would state that fact somewhere. Reading it again to me it sounds a lot like the search_tweets function would download all the available tweets relating to a query (oviously within the 6-9 days and below the rate cap).

Best regards, 
Leon

**Comment by llrs** [comment]
@LeonStumberger yes maybe I could add that if users misunderstand the API. But I cannot copy the whole API documentation in the package, there is a link to the official documentation at the bottom of each help page for cases like this.
