### ISSUE TITLE
RTweet support for looking up blocked users as well as unblocking / blocking users. 

### ISSUE THREAD

**Issue by llrs** [ropensci/rtweet#752]
Original petition in Twitter by @majesticprimate, it requires API v2

**Comment by majesticprimate** [comment]
Thank you - awesome!

**Comment by llrs** [comment]
Sorry, I think I mislead you. This is not in rtweet yet, I just closed the pull requests #748 and opened this issue to remind me of it. I closed the PR because I think it caused a couple of problems while testing the package.

**Comment by majesticprimate** [comment]
Hi Lluís. No problem - you didn’t mislead me, rather I misread the notification. Is there any chance it will make it in an upcoming release?On Dec 11, 2022, at 02:15, Lluís Revilla ***@***.***> wrote:﻿
Sorry, I think I mislead you. This is not in rtweet yet, I just closed the pull requests #748 and opened this issue to remind me of it. I closed the PR because I think it caused a couple of problems while testing the package.

**Comment by llrs** [comment]
I am afraid it won't. I don't have enough time to work in it this week (next release will be around the end of the week). I want to fix other features I want to release and I've been working for longer.

**Comment by majesticprimate** [comment]
Alright thanks for letting me know. Hopefully you can get it back on the books later.On Dec 12, 2022, at 17:11, Lluís Revilla ***@***.***> wrote:﻿
I am afraid it won't. I don't have enough time to work in it this week (next release will be around the end of the week). I want to fix other features I want to release and I've been working for longer.

**Comment by llrs** [comment]
One can already look for blocked users via [`user_blocked()`](https://docs.ropensci.org/rtweet/reference/user_blocked.html) if you have the basic account. Closing it as I cannot test for the remaining endpoints
