### ISSUE TITLE
Persistent 401 Error in Rtweet

### ISSUE THREAD

**Issue by knelson3-trinity** [ropensci/rtweet#769]
I have academic access to Twitter. On February 14 (the last time I worked on my project), I received authentication by running the below code (where app name and keys are their actual strings, not the word "INSERT"):  
my_auth<-rtweet::create_token(rtweet::create_token(app = "INSERT", 
                                                   consumer_key = "INSERT",
                                                   consumer_secret = "INSERT", 
                                                   access_token="INSERT", 
                                                   access_secret = "INSERT"))
When I ran identical code on April 6, I get the following 401 error: "Error in httr::init_oauth1.0(endpoint, app, permission = permission, is_interactive = is_interactive,  : Unauthorized (HTTP 401)." 

I've tried the following: 
1. regenerating and re-entering the consumer key, consumer secret, access token, and access secret
2. using a different version of retweet install.packages("rtweet", repos = 'https://ropensci.r-universe.dev/'), pursuant to the recommendations from this thread: https://github.com/ropensci/rtweet/issues/756.

Both method 1 and 2 had no effect. 

A third method, recommended in this thread (https://github.com/ropensci/rtweet/issues/204), is to turn off "callback looping" on my app. Despite extensive google searching and scouring my app, I simply cannot figure out how to do this. If folks believe this is likely to solve my problem (it seemed to have a roughly 50-50 chance of doing so as per the above thread),  I would greatly appreciate info on how to turn off "callback looping." If something else entirely is the issue, I'd appreciate any advice.

**Comment by llrs** [comment]
As explained in [one comment of the linked issues](https://github.com/ropensci/rtweet/issues/756#issuecomment-1497464678) the default app was banned from twitter.

If you are trying to create your own, it will probably not work because recently there have been changes in the API access (I assume that using `create_token(create_token())` is just a copy paste error). This could be a problem with their servers too. 

The callback looping is a very old reference that I think is no longer relevant to rtweet as it is now.

I would recommend to use rtweet_app or rtweet_oauth2 authentication mechanisms.

**Comment by llrs** [comment]
Closing as I haven't heard back
